spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mysql://localhost:3306/pharmacydb
    username: root
    password: Hari@8975
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
store:
  storeNo: 5000
  storeName: medplus
  storeManager: Rakesh
  openHours: 10
  openMinutes: 30
  closingHours: 10
  closingMinutes: 00
  location: "Panjagutta, Hyderabad"